#[cfg(target_os = "macos")]
pub mod adapter;
#[cfg(target_os = "macos")]
pub mod app_blocker;
#[cfg(target_os = "macos")]
pub mod dns_proxy;
#[cfg(target_os = "macos")]
pub mod permissions;
#[cfg(target_os = "macos")]
pub mod workspace_monitor;
