[package]
name = "zen-db"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
zen-domain = { path = "../zen-domain" }
zen-core = { path = "../zen-core" }
sqlx = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
time = { workspace = true }
uuid = { workspace = true }
